# Generated by Django 5.2.6 on 2025-09-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_done_it_alter_task_end_at_alter_task_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='autor',
            new_name='user',
        ),
    ]
