# Generated by Django 5.2.6 on 2025-09-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_created_at_alter_task_end_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='done_it',
            new_name='completed',
        ),
    ]
