# Generated by Django 5.2.6 on 2025-09-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_rename_done_it_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='end_at',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
